### PR TITLE
ci(delivery): fix

### PR DESCRIPTION
**Pull request by RealShadowNova**

### CODE REVIEW

**Review by dan-online — COMMENTED** [review]
Question: could GitHub tags be pushed to the GitHub repo when we publish? with changelog descriptions?

**Comment by RealShadowNova** [comment]
> Question: could GitHub tags be pushed to the GitHub repo when we publish? with changelog descriptions?

wdym exactly? the changelog just lists the commits, which would be pointless here.

**Comment by dan-online** [comment]
> > Question: could GitHub tags be pushed to the GitHub repo when we publish? with changelog descriptions?
> 
> 
> 
> wdym exactly? the changelog just lists the commits, which would be pointless here.

No so, when you npm version, it auto makes a tag- but can we push those, also auto "releases" with the changelog attached is what I meant

**Comment by RealShadowNova** [comment]
> > > Question: could GitHub tags be pushed to the GitHub repo when we publish? with changelog descriptions?
> > 
> > 
> > wdym exactly? the changelog just lists the commits, which would be pointless here.
> 
> No so, when you npm version, it auto makes a tag- but can we push those, also auto "releases" with the changelog attached is what I meant

That is done only when we start releasing non-next versions

**Comment by dan-online** [comment]
> > > > Question: could GitHub tags be pushed to the GitHub repo when we publish? with changelog descriptions?
> 
> > > 
> 
> > > 
> 
> > > wdym exactly? the changelog just lists the commits, which would be pointless here.
> 
> > 
> 
> > No so, when you npm version, it auto makes a tag- but can we push those, also auto "releases" with the changelog attached is what I meant
> 
> 
> 
> That is done only when we start releasing non-next versions

Right and is that setup already?

**Comment by RealShadowNova** [comment]
Yes, but still need to figure out how were going to use `stable` branch later on. Anyways, unrelated to this PR, but yeah will be done.

**Review by dan-online — APPROVED** [review]
LGTM

**Pull request merged**
